# Generated by Django 4.2 on 2025-11-11 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_room_description_room_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='include_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='include_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='include_spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
