# Generated by Django 4.2 on 2025-11-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_include_gym_booking_include_pool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='include_gym',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='include_pool',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='include_spa',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
    ]
